version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: junin317/trace:1.0
    container_name: app_container
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:tracing:mysql://mysql:3306/tracedb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
      - jaeger
    command: [ "-c","/app/wait-for-mysql.sh mysql:3306 && java -jar /app/app.jar" ]
    entrypoint: [ "/bin/sh" ]

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracedb

  jaeger:
    image: jaegertracing/all-in-one:1.23
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411